language: java
dist: trusty
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk11
  - openjdk13
  - openjdk-ea

install: "mvn clean test"

after_success:
  - mvn clean cobertura:cobertura -Dcobertura.report.format=xml org.eluder.coveralls:coveralls-maven-plugin:report -DcoberturaReports=target/site/cobertura/cobertura.xml
