language: java
dist: trusty
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk11
  - openjdk13
  - openjdk-ea


matrix:
  include:
    - os: linux-ppc64le
      jdk: openjdk8
  allow_failures:
    - jdk: openjdk-ea

script:
  - mvn

after_success:
  - mvn clean cobertura:cobertura -Dcobertura.report.format=xml org.eluder.coveralls:coveralls-maven-plugin:report -DcoberturaReports=target/site/cobertura/cobertura.xml
