From: Bruno P. Kinoshita <brunodepaulak@yahoo.com.br>
To: tap4j@lists.sourceforge.net
Subject: [ANN] tap4j 4.0 is available

==========================
 Announcing tap4j-4.0
==========================

A new release of tap4j is now available:

    http://www.tap4j.org

This release delivers a new recursive descent parser as well as other minor 
changes and bug fixes.

The complete list of changes is here: http://www.tap4j.org/changes-report.html 

Resources
==========

tap4j homepage: http://www.tap4j.org
tap4j book: http://www.tap4j.org/book

JAR package: http://repo2.maven.org/maven2/org/tap4j/tap4j/4.0/tap4j-4.0.jar
Reports: http://www.tap4j.org/project-reports.html

tap4j git repository: https://github.com/tupilabs/tap4j
Submit a bug report: https://github.com/tupilabs/tap4j/issues/new

TAP homepage: http://testanything.org/
TAP mailing list: http://testanything.org/mailman/listinfo/tap-l

About tap4j
================

tap4j was created in 2010 with the intention of implementing a producer and a 
consumer for TAP in Java. In 2012 it was rewritten, using SnakeYAML as 
reference.

Copyright
==========
tap4j is released under the MIT License
