//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 07:47:15 AM CET 
//


package org.tap4j.ext.jmeter.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Sample complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Sample">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractSample">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="httpSample" type="{}HttpSample"/>
 *           &lt;element name="sample" type="{}Sample"/>
 *         &lt;/choice>
 *         &lt;element name="responseHeader" type="{}TextEl" minOccurs="0"/>
 *         &lt;element name="requestHeader" type="{}TextEl" minOccurs="0"/>
 *         &lt;element name="responseData" type="{}TextEl" minOccurs="0"/>
 *         &lt;element name="responseFile" type="{}TextEl" minOccurs="0"/>
 *         &lt;element name="samplerData" type="{}TextEl" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Sample", propOrder = {
    "httpSampleOrSample",
    "responseHeader",
    "requestHeader",
    "responseData",
    "responseFile",
    "samplerData"
})
public class Sample
    extends AbstractSample
{

    @XmlElements({
        @XmlElement(name = "httpSample", type = HttpSample.class),
        @XmlElement(name = "sample", type = Sample.class)
    })
    protected List<AbstractSample> httpSampleOrSample;
    protected TextEl responseHeader;
    protected TextEl requestHeader;
    protected TextEl responseData;
    protected TextEl responseFile;
    protected TextEl samplerData;

    /**
     * Gets the value of the httpSampleOrSample property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the httpSampleOrSample property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHttpSampleOrSample().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HttpSample }
     * {@link Sample }
     * 
     * 
     */
    public List<AbstractSample> getHttpSampleOrSample() {
        if (httpSampleOrSample == null) {
            httpSampleOrSample = new ArrayList<AbstractSample>();
        }
        return this.httpSampleOrSample;
    }

    /**
     * Gets the value of the responseHeader property.
     * 
     * @return
     *     possible object is
     *     {@link TextEl }
     *     
     */
    public TextEl getResponseHeader() {
        return responseHeader;
    }

    /**
     * Sets the value of the responseHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextEl }
     *     
     */
    public void setResponseHeader(TextEl value) {
        this.responseHeader = value;
    }

    /**
     * Gets the value of the requestHeader property.
     * 
     * @return
     *     possible object is
     *     {@link TextEl }
     *     
     */
    public TextEl getRequestHeader() {
        return requestHeader;
    }

    /**
     * Sets the value of the requestHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextEl }
     *     
     */
    public void setRequestHeader(TextEl value) {
        this.requestHeader = value;
    }

    /**
     * Gets the value of the responseData property.
     * 
     * @return
     *     possible object is
     *     {@link TextEl }
     *     
     */
    public TextEl getResponseData() {
        return responseData;
    }

    /**
     * Sets the value of the responseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextEl }
     *     
     */
    public void setResponseData(TextEl value) {
        this.responseData = value;
    }

    /**
     * Gets the value of the responseFile property.
     * 
     * @return
     *     possible object is
     *     {@link TextEl }
     *     
     */
    public TextEl getResponseFile() {
        return responseFile;
    }

    /**
     * Sets the value of the responseFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextEl }
     *     
     */
    public void setResponseFile(TextEl value) {
        this.responseFile = value;
    }

    /**
     * Gets the value of the samplerData property.
     * 
     * @return
     *     possible object is
     *     {@link TextEl }
     *     
     */
    public TextEl getSamplerData() {
        return samplerData;
    }

    /**
     * Sets the value of the samplerData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextEl }
     *     
     */
    public void setSamplerData(TextEl value) {
        this.samplerData = value;
    }

}
